apiVersion: v1
kind: Service
metadata:
  name: frontendflights
spec:
  selector:
    app: frontendflights
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
